### PR TITLE
merge upstream changes (including support for Xcode 12)

### PR DESCRIPTION
**Pull request by mykmelez**
Now that upstream has been adopted and is being actively maintained, let's incorporate its latest changes!

### CODE REVIEW

**Review by Chondrules — APPROVED** [review]
⬆️

**Comment by jnross** [comment]
Do we have any changes in our fork that add value beyond the upstream repo?  Maybe we should submit those as a PR and disband our fork or keep it in tight sync with upstream?

**Comment by mykmelez** [comment]
@jnross, there are no longer any differences between our fork and upstream. Before being adopted, the old owner finally merged (or closed as duplicate) the pull requests we'd submitted over many months, so we no longer have any changes. Thus we can disband our fork or keep it in sync, as desired.

**Comment by jnross** [comment]
As usual, you're ahead of me.  Nice!

**Pull request merged**
